// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// convolve5cpp
Rcpp::NumericVector convolve5cpp(Rcpp::NumericVector& xa, Rcpp::NumericVector& xb);
RcppExport SEXP _optimisedpkgWithRcpp_convolve5cpp(SEXP xaSEXP, SEXP xbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type xa(xaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector& >::type xb(xbSEXP);
    rcpp_result_gen = Rcpp::wrap(convolve5cpp(xa, xb));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_optimisedpkgWithRcpp_convolve5cpp", (DL_FUNC) &_optimisedpkgWithRcpp_convolve5cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_optimisedpkgWithRcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
